### ISSUE TITLE
Config Problems Having Both Python 2 and 3

### ISSUE THREAD

**Issue by xevix** [tailhook/coyaml#2]
Even though I force use of python3, it finds Python 2, takes that for its version, and aborts.

<pre>
$ python3 ./waf configure --prefix=/usr
Setting top to                           : /home/xevix/coyaml 
Setting out to                           : /home/xevix/coyaml/build 
Checking for 'gcc' (c compiler)          : ok 
Checking for program python              : /usr/bin/python 
python executable '/usr/bin/python' different from sys.executable '/usr/bin/python3'
Checking for python version              : (2, 7, 1, 'final', 0) 
The python version is too old, expecting (3, 0, 0)
(complete log in /home/xevix/coyaml/build/config.log)
</pre>

**Comment by tailhook** [comment]
you need to prefix your configure line with `PYTHON=python3` (updated `README` too)
