### ISSUE TITLE
AttributeError: Can't pickle local object 'Context.__init__.<locals>.node_class'

### ISSUE THREAD

**Issue by MFeldtmann** [tailhook/coyaml#4]
This is the error I get when executing

python3 ./waf build

unter Ubuntu 16.04 (64bit)

**Comment by tailhook** [comment]
Hi. I can reproduce it, but i'm not sure why it happens.

Honestly, I don't maintain this project any more, since I'm moving on to using Rust for my systems level stuff.

Do you want to use coyaml in the new project or are you trying to build some other project that uses it?

**Comment by praveenlobo** [comment]
Use latest version of waf-light (https://gitlab.com/ita1024/waf/) to fix this issue.
